### PR TITLE
WarClans612 hw1

### PR DESCRIPTION
**Pull request by WarClans612**

### CODE REVIEW

**Comment by tigercosmos** [comment]
@WarClans612  your handling for `python0`  is wrong.

**Comment by WarClans612** [comment]
@tigercosmos can I know what is wrong?
 It seems that I get full point using validation script and my code has returned error code when used with `python0`

**Comment by tigercosmos** [comment]
@WarClans612 the correct behavior is returning "python0 doesn't exist" when you run the command rather than get the error whole message. in other words, you need to handle the case rather than let it output errors.

**Comment by tigercosmos** [comment]
the CI doesn't cover 100%, so the TA will check the code as well and modify the score.

**Comment by WarClans612** [comment]
@tigercosmos Updated

**Pull request closed without merging**
