### PR TITLE
Add hw1 files

### PR DESCRIPTION
**Pull request by AilurusUmbra**

### CODE REVIEW

**Comment by tigercosmos** [comment]
why do you open two PR for hw1?

**Comment by AilurusUmbra** [comment]
I am not sure whether we have to modify branch name to `<username>-hw1-attempt1` or this doesn't matter.
This 2 PRs are identical except the branch name on my repo.

**Comment by tigercosmos** [comment]
it doesn't matter. Make sure you submit the right URL of the PR on E3. Please close either one.

**Comment by AilurusUmbra** [comment]
Got it, thanks!

**Pull request merged**
