### PR TITLE
yanagiragi-ci-enhance

### LINKED ISSUE #16: Enhancement of Action CI for individual testing
I would like to propose a enhancement on action CI. It would be nice to slightly change ```hw1.yml``` to [this](https://gist.github.com/yanagiragi/1b68829766abe4857f765d980cb9d93f). The main difference is to replace ```$GITHUB_REF``` to ```$GITHUB_REPOSITORY```.

With the change, we'll be able to test ourselves on our repository. Previous way getting ```$username``` using ```$GITHUB_REF``` are not able to achieve this. In the [previous test](https://github.com/yungyuc/nsdhw_20sp/runs/497196220?check_suite_focus=true), the action is passes since the branch name is 'yungyuc-hw1-submit-example', but in most cases the branch may not be this format (hw1, hw2, etc.). Using ```$GITHUB_REPOSITORY``` will still do the same trick but allowed students to test individually on their own forked repository. To avoid breaks after the change, I listed the possible conditions came up my mind in the below.

1. **[Behaviour changed!]** If the push is from the collaborator or the owner of base repo, e.g. @tigercosmos push a commit to yungyuc/nsdhw_20sp on branch _hw1_. The change should work well considering the output of ```$GITHUB_REPOSITORY``` in [this](https://github.com/yungyuc/nsdhw_20sp/runs/500834789?check_suite_focus=true) test.

2. **[Behaviour changed!]** If the push is from owner of forked repo to the forked repo, e.g. @yanagiragi push a commit to yanagiragi/nsdhw_20sp on branch _hw1_. The changes worked well in [here](https://github.com/yanagiragi/nsdhw_20sp/runs/501329305?check_suite_focus=true).

3. **[Behaviour changed!]** If the PR is from owner in base repo, e.g. @yungyuc send a PR from yungyuc/nsdhw_20sp branch _whatever_ to yungyuc/nsdhw_20sp on branch _hw1_. The change should work well considering the output of ```$GITHUB_REPOSITORY``` in [this](https://github.com/yungyuc/nsdhw_20sp/runs/499404877?check_suite_focus=true) test.

4. If the PR is from owner in forked repo, e.g. @yanagiragi send a PR from yanagiragi/nsdhw_20sp to yungyuc/nsdhw_20sp on branch _hw1_. The change did not break in [here](https://github.com/yungyuc/nsdhw_20sp/actions/runs/53826199).

Condition 1 and 3 has not been tested since I do not have the permission. Current solution does not support the collaborator to submit tests on it directiory (e.g. @tigercosmos wish to test hw1.yml action with files in hw1/tigercosmos on yungyuc/osd_20sp branch _hw1_ ). The collaborator might need to fork the project and test the action CI like other students.

### PR DESCRIPTION
**Pull request by yanagiragi**
Solving #16.

close #16 
close #18
close #19
close #21

### CODE REVIEW

**Comment by tigercosmos** [comment]
LGTM

**Comment by tigercosmos** [comment]
@yanagiragi  Could you check the PR above. Seems it doesn't get the right username.

**Comment by yanagiragi** [comment]
@tigercosmos Thank for pointing out. I push a new commit to fix the issue. I think the behavior of two tests in a PR will be consistent for now.

**Comment by tigercosmos** [comment]
@yanagiragi  seems you push another commit. Ping me when you have done it.

**Comment by yanagiragi** [comment]
@tigercosmos I'm done. [faaa8e7](https://github.com/yungyuc/nsdhw_20sp/pull/17/commits/faaa8e7d6d04f8ca03d531bbad29554e760a618f) should fix the bug. Hope it works.

**Comment by tigercosmos** [comment]
@yanagiragi  thanks.

**Comment by yanagiragi** [comment]
@tigercosmos Just to remind you that the branch hw1 hasn't sync with master, so current the patch may not work yet.

**Comment by tigercosmos** [comment]
@yanagiragi  ok. It's synced now.

**Pull request merged**
