### PR TITLE
WarClans612 hw3

### PR DESCRIPTION
**Pull request by WarClans612**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by tigercosmos** [comment]
@WarClans612  You use two different data for testing two functions.

The goal is to see the performance difference, we would like to decrease any factors that affect the result.
Therefore, you would like to create data sets first, and use the **same** data sets for testing.

**Comment by tigercosmos** [comment]
you may need to fix this to get 5.

**Comment by WarClans612** [comment]
@tigercosmos 
The matrix for performance testing is initialized in [Matrix Initialization Code Line](https://github.com/WarClans612/nsdhw_20sp/blob/20c54546b6683f8470b23cf9073b2d81ec042d43/hw3/WarClans612/test_matrix.py#L38-L45).

And [Timing Code Line](https://github.com/WarClans612/nsdhw_20sp/blob/20c54546b6683f8470b23cf9073b2d81ec042d43/hw3/WarClans612/test_matrix.py#L47-L59) is only responsible for multiplying the matrix. Therefore, it should already be using **the same** datasets.

If I am mistaken, can you clarify at which line do you see the problem? Thanks

**Comment by tigercosmos** [comment]
yeah. You were right!
I misunderstood the code before.

Then it's all right. You got 5. :)

**Pull request merged**
